plugins {
    id "com.android.application"
}

android {
    namespace "t8numen.screenshotfirewall"
    compileSdk 35

    defaultConfig {
        applicationId "t8numen.screenshotfirewall"
        minSdk 24
        targetSdk 35
        versionCode 24
        versionName "1.0.23"
    }
}

dependencies {
    compileOnly "de.robv.android.xposed:api:82"
}
